export default [
  { value: '9', suit: 'spades', color: 'black', description: '9 of spades' },
  { value: '10', suit: 'spades', color: 'black', description: '10 of spades' },
  {
    value: 'Jack',
    suit: 'spades',
    color: 'black',
    description: 'Jack of spades',
  },
  {
    value: 'Queen',
    suit: 'spades',
    color: 'black',
    description: 'Queen of spades',
  },
  {
    value: 'King',
    suit: 'spades',
    color: 'black',
    description: 'King of spades',
  },
  {
    value: 'Ace',
    suit: 'spades',
    color: 'black',
    description: 'Ace of spades',
  },
  { value: '9', suit: 'hearts', color: 'red', description: '9 of hearts' },
  { value: '10', suit: 'hearts', color: 'red', description: '10 of hearts' },
  {
    value: 'Jack',
    suit: 'hearts',
    color: 'red',
    description: 'Jack of hearts',
  },
  {
    value: 'Queen',
    suit: 'hearts',
    color: 'red',
    description: 'Queen of hearts',
  },
  {
    value: 'King',
    suit: 'hearts',
    color: 'red',
    description: 'King of hearts',
  },
  { value: 'Ace', suit: 'hearts', color: 'red', description: 'Ace of hearts' },
  { value: '9', suit: 'clubs', color: 'black', description: '9 of clubs' },
  { value: '10', suit: 'clubs', color: 'black', description: '10 of clubs' },
  {
    value: 'Jack',
    suit: 'clubs',
    color: 'black',
    description: 'Jack of clubs',
  },
  {
    value: 'Queen',
    suit: 'clubs',
    color: 'black',
    description: 'Queen of clubs',
  },
  {
    value: 'King',
    suit: 'clubs',
    color: 'black',
    description: 'King of clubs',
  },
  { value: 'Ace', suit: 'clubs', color: 'black', description: 'Ace of clubs' },
  { value: '9', suit: 'diamonds', color: 'red', description: '9 of diamonds' },
  {
    value: '10',
    suit: 'diamonds',
    color: 'red',
    description: '10 of diamonds',
  },
  {
    value: 'Jack',
    suit: 'diamonds',
    color: 'red',
    description: 'Jack of diamonds',
  },
  {
    value: 'Queen',
    suit: 'diamonds',
    color: 'red',
    description: 'Queen of diamonds',
  },
  {
    value: 'King',
    suit: 'diamonds',
    color: 'red',
    description: 'King of diamonds',
  },
  {
    value: 'Ace',
    suit: 'diamonds',
    color: 'red',
    description: 'Ace of diamonds',
  },
];
